cs202hw2: BST.o BSTNode.o analysis.o main.o
		g++ BST.o BSTNode.o analysis.o main.o -o cs202hw2

BST.o : BST.cpp
		g++ -c BST.cpp
		
BSTNode.o : BSTNode.cpp
		g++ -c BSTNode.cpp
		
analysis.o :  analysis.cpp
		g++ -c analysis.cpp

main.o : main.cpp
		g++ -c main.cpp